2021-11-20 08:54:06,766 INFO    MainThread:3881 [wandb_setup.py:_flush():71] setting env: {}
2021-11-20 08:54:06,766 INFO    MainThread:3881 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 08:54:06,766 INFO    MainThread:3881 [wandb_init.py:_log_setup():357] Logging user logs to /home/dev/classification/wandb/run-20211120_085406-qvqhcms0/logs/debug.log
2021-11-20 08:54:06,767 INFO    MainThread:3881 [wandb_init.py:_log_setup():358] Logging internal logs to /home/dev/classification/wandb/run-20211120_085406-qvqhcms0/logs/debug-internal.log
2021-11-20 08:54:06,767 INFO    MainThread:3881 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f98140e8940>
2021-11-20 08:54:06,768 INFO    MainThread:3881 [wandb_init.py:init():390] calling init triggers
2021-11-20 08:54:06,768 INFO    MainThread:3881 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-20 08:54:06,768 INFO    MainThread:3881 [wandb_init.py:init():435] starting backend
2021-11-20 08:54:06,768 INFO    MainThread:3881 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-20 08:54:06,809 INFO    MainThread:3881 [backend.py:ensure_launched():199] starting backend process...
2021-11-20 08:54:06,840 INFO    MainThread:3881 [backend.py:ensure_launched():205] started backend process with pid: 4157
2021-11-20 08:54:06,842 INFO    MainThread:3881 [wandb_init.py:init():444] backend started and connected
2021-11-20 08:54:06,845 INFO    MainThread:3881 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-11-20 08:54:06,846 INFO    MainThread:3881 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-20 08:54:06,846 INFO    MainThread:3881 [wandb_init.py:init():503] updated telemetry
2021-11-20 08:54:06,847 INFO    MainThread:3881 [wandb_init.py:init():533] communicating current version
2021-11-20 08:54:07,881 INFO    MainThread:3881 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.12.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-20 08:54:07,883 INFO    MainThread:3881 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-20 08:54:07,976 INFO    MainThread:3881 [wandb_init.py:init():576] starting run threads in backend
2021-11-20 08:54:09,931 INFO    MainThread:3881 [wandb_run.py:_console_start():1693] atexit reg
2021-11-20 08:54:09,932 INFO    MainThread:3881 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-11-20 08:54:09,938 INFO    MainThread:3881 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-11-20 08:54:09,939 INFO    MainThread:3881 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-20 08:54:09,939 INFO    MainThread:3881 [wandb_init.py:init():603] run started, returning control to user process
2021-11-20 08:54:18,597 INFO    MainThread:3881 [wandb_init.py:_pause_backend():270] pausing backend
2021-11-20 08:54:18,598 INFO    MainThread:3881 [jupyter.py:save_ipynb():374] not saving jupyter notebook
